// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_R-Y44_re4Yr2t7oXRsl_SjQRWmBSCA',
    appId: '1:879903323781:web:fabb651e2579c09ac6dbec',
    messagingSenderId: '879903323781',
    projectId: 'fir-8b033',
    authDomain: 'fir-8b033.firebaseapp.com',
    storageBucket: 'fir-8b033.appspot.com',
    measurementId: 'G-EY13ZSDT2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGRC7NV4aRnB--RMmsvZq4ePgYnM7Ly8Q',
    appId: '1:879903323781:android:14ae34a0055114d5c6dbec',
    messagingSenderId: '879903323781',
    projectId: 'fir-8b033',
    storageBucket: 'fir-8b033.appspot.com',
  );

}