# Name of the workflow
name: Unit and Integration tests

# This workflow is triggered when pull requests are opened or updated
on: [pull_request]

jobs:
  android:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        api-level: ["29"]
      fail-fast: true
      
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Java 17
      - name: Java 17 Setup
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17.x"

      # Set up Flutter SDK
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.1"
          channel: "stable"

      # Set up Node.js for the server
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install server dependencies
      - name: Install Node.js Dependencies
        run: npm install
        working-directory: ./ # Update if the server is in a subdirectory

      # Start Node.js server
      - name: Start Node.js Server
        run: nohup node server.js > server.log 2>&1 &
        working-directory: ./ # Update if server.js is in a different directory

      # Wait for server to start
      - name: Wait for Server to Start
        run: |
          sleep 10
          curl http://localhost:3000/login || exit 1

      # Run Unit Tests
      - name: Run Unit Tests
        run: flutter test

      # Run Integration Tests using Android Emulator
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --target=test_driver/app.dart

      # Stop Node.js server
      - name: Stop Node.js Server
        run: |
          kill $(lsof -t -i:3000) || echo "No server running on port 3000"
